[package]
name = "suballoc"
version = "0.1.4"
edition = "2024"

[dependencies]
rand = "0.10.0-rc.0"
bytemuck = "1.23.2"

[profile.dev]
strip = false
debug = true

[profile.release]
strip = false
debug = true
lto = "fat"